import {
  snippetCompletion,
  type CompletionContext,
} from "@codemirror/autocomplete";

const typstOptions = [

    snippetCompletion("let ${name} = ${value}", { label: "let", type: "keyword", info: "Variable declaration" }),
    snippetCompletion("set ${rule}(${value})", { label: "set", type: "keyword", info: "Set rule" }),
    snippetCompletion("show ${selector}: ${rule}", { label: "show", type: "keyword", info: "Show rule" }),
    snippetCompletion("import \"${module}\": ${items}", { label: "import", type: "keyword", info: "Import module" }),
    snippetCompletion("include \"${file}\"", { label: "include", type: "keyword", info: "Include file" }),
    snippetCompletion("if ${condition} {\n\t${}\n}", { label: "if", type: "keyword", info: "If statement" }),
    snippetCompletion("else {\n\t${}\n}", { label: "else", type: "keyword", info: "Else statement" }),
    snippetCompletion("for ${item} in ${collection} {\n\t${}\n}", { label: "for", type: "keyword", info: "For loop" }),
    snippetCompletion("while ${condition} {\n\t${}\n}", { label: "while", type: "keyword", info: "While loop" }),
    snippetCompletion("break", { label: "break", type: "keyword", info: "Break loop" }),
    snippetCompletion("continue", { label: "continue", type: "keyword", info: "Continue loop" }),
    snippetCompletion("return ${value}", { label: "return", type: "keyword", info: "Return value" }),
    snippetCompletion("context", { label: "context", type: "keyword", info: "Context expression" }),
    snippetCompletion("align(${alignment})[${content}]", { label: "align", type: "function", info: "Align content" }),
    snippetCompletion("page(${content})", { label: "page", type: "function", info: "Page configuration" }),
    snippetCompletion("pagebreak()", { label: "pagebreak", type: "function", info: "Break page" }),
    snippetCompletion("colbreak()", { label: "colbreak", type: "function", info: "Break column" }),
    snippetCompletion("place(${alignment})[${content}]", { label: "place", type: "function", info: "Place content" }),
    snippetCompletion("columns(${2})[${content}]", { label: "columns", type: "function", info: "Multiple columns" }),
    snippetCompletion("pad(${10pt})[${content}]", { label: "pad", type: "function", info: "Pad content" }),
    snippetCompletion("stack(dir: ${ttb}, spacing: ${10pt}, ${items})", { label: "stack", type: "function", info: "Stack items" }),
    snippetCompletion("grid(columns: ${2}, gutter: ${10pt}, ${items})", { label: "grid", type: "function", info: "Grid layout" }),
    snippetCompletion("table(columns: ${2}, ${items})", { label: "table", type: "function", info: "Table layout" }),
    snippetCompletion("rect(width: ${100%}, height: ${100%})[${content}]", { label: "rect", type: "function", info: "Draw rectangle" }),
    snippetCompletion("square(size: ${10pt})[${content}]", { label: "square", type: "function", info: "Draw square" }),
    snippetCompletion("circle(radius: ${10pt})[${content}]", { label: "circle", type: "function", info: "Draw circle" }),
    snippetCompletion("ellipse(width: ${20pt}, height: ${10pt})[${content}]", { label: "ellipse", type: "function", info: "Draw ellipse" }),
    snippetCompletion("line(length: ${100%})", { label: "line", type: "function", info: "Draw line" }),
    snippetCompletion("polygon(${vertices})", { label: "polygon", type: "function", info: "Draw polygon" }),
    snippetCompletion("path(${vertices})", { label: "path", type: "function", info: "Draw path" }),
    snippetCompletion("image(\"${path}\", width: ${100%})", { label: "image", type: "function", info: "Insert image" }),
    snippetCompletion("box[${content}]", { label: "box", type: "function", info: "Box inline content" }),
    snippetCompletion("block[${content}]", { label: "block", type: "function", info: "Block content" }),
    snippetCompletion("figure(${content}, caption: [${caption}])", { label: "figure", type: "function", info: "Figure with caption" }),
    snippetCompletion("text(size: ${11pt}, font: \"${Arial}\")[${content}]", { label: "text", type: "function", info: "Text styling" }),
    snippetCompletion("heading(level: ${1})[${title}]", { label: "heading", type: "function", info: "Heading" }),
    snippetCompletion("par[${content}]", { label: "par", type: "function", info: "Paragraph" }),
    snippetCompletion("list([${item}])", { label: "list", type: "function", info: "Bullet list" }),
    snippetCompletion("enum([${item}])", { label: "enum", type: "function", info: "Numbered list" }),
    snippetCompletion("terms([${term}], [${description}])", { label: "terms", type: "function", info: "Terms list" }),
    snippetCompletion("strong[${content}]", { label: "strong", type: "function", info: "Bold text" }),
    snippetCompletion("emph[${content}]", { label: "emph", type: "function", info: "Italic text" }),
    snippetCompletion("underline[${content}]", { label: "underline", type: "function", info: "Underline text" }),
    snippetCompletion("strike[${content}]", { label: "strike", type: "function", info: "Strikethrough text" }),
    snippetCompletion("overline[${content}]", { label: "overline", type: "function", info: "Overline text" }),
    snippetCompletion("sub[${content}]", { label: "sub", type: "function", info: "Subscript text" }),
    snippetCompletion("super[${content}]", { label: "super", type: "function", info: "Superscript text" }),
    snippetCompletion("raw(\"${code}\", block: ${true})", { label: "raw", type: "function", info: "Raw code block" }),
    snippetCompletion("link(\"${url}\")[${text}]", { label: "link", type: "function", info: "Hyperlink" }),
    snippetCompletion("ref(<${label}>)", { label: "ref", type: "function", info: "Reference" }),
    snippetCompletion("cite(<${label}>)", { label: "cite", type: "function", info: "Citation" }),
    snippetCompletion("bibliography(\"${file.bib}\")", { label: "bibliography", type: "function", info: "Bibliography" }),
    snippetCompletion("outline(title: [${Contents}])", { label: "outline", type: "function", info: "Table of contents" }),
    snippetCompletion("rgb(\"${#000000}\")", { label: "rgb", type: "function", info: "RGB Color" }),
    snippetCompletion("cmyk(${0%}, ${0%}, ${0%}, ${100%})", { label: "cmyk", type: "function", info: "CMYK Color" }),
    snippetCompletion("luma(${0%})", { label: "luma", type: "function", info: "Luma (Grayscale) Color" }),
    snippetCompletion("color", { label: "color", type: "variable" }),
    snippetCompletion("gradient", { label: "gradient", type: "variable" }),
    snippetCompletion("pattern(size: (${10pt}, ${10pt}))[${content}]", { label: "pattern", type: "function", info: "Fill pattern" }),
    snippetCompletion("type(${value})", { label: "type", type: "function", info: "Get type of value" }),
    snippetCompletion("repr(${value})", { label: "repr", type: "function", info: "String representation" }),
    snippetCompletion("str(${value})", { label: "str", type: "function", info: "Convert to string" }),
    snippetCompletion("int(${value})", { label: "int", type: "function", info: "Convert to integer" }),
    snippetCompletion("float(${value})", { label: "float", type: "function", info: "Convert to float" }),
    snippetCompletion("datetime(year: ${2024}, month: ${1}, day: ${1})", { label: "datetime", type: "function", info: "Date and time" }),
    snippetCompletion("math", { label: "math", type: "variable", info: "Math module" }),
    snippetCompletion("calc", { label: "calc", type: "variable", info: "Calc module" }),
    snippetCompletion("sys", { label: "sys", type: "variable", info: "System module" }),
    snippetCompletion("frac(${num}, ${denom})", { label: "frac", type: "function", info: "Fraction (Math)" }),
    snippetCompletion("binom(${n}, ${k})", { label: "binom", type: "function", info: "Binomial (Math)" }),
    snippetCompletion("mat(${1}, ${2}; ${3}, ${4})", { label: "mat", type: "function", info: "Matrix (Math)" }),
    snippetCompletion("vec(${1}, ${2})", { label: "vec", type: "function", info: "Vector (Math)" }),
    snippetCompletion("cases(${a}, ${b})", { label: "cases", type: "function", info: "Cases (Math)" }),
    snippetCompletion("sqrt(${x})", { label: "sqrt", type: "function", info: "Square root (Math)" }),
    snippetCompletion("root(${3}, ${x})", { label: "root", type: "function", info: "N-th root (Math)" }),
    snippetCompletion("abs(${x})", { label: "abs", type: "function", info: "Absolute value (Math)" }),
    snippetCompletion("norm(${x})", { label: "norm", type: "function", info: "Norm (Math)" }),
    snippetCompletion("floor(${x})", { label: "floor", type: "function", info: "Floor (Math)" }),
    snippetCompletion("ceil(${x})", { label: "ceil", type: "function", info: "Ceiling (Math)" }),
    snippetCompletion("round(${x})", { label: "round", type: "function", info: "Round (Math)" }),
    snippetCompletion("cancel(${x})", { label: "cancel", type: "function", info: "Cancel/strike (Math)" }),
    snippetCompletion("attach(${base}, t: ${top}, b: ${bottom})", { label: "attach", type: "function", info: "Attach scripts (Math)" }),
    snippetCompletion("scripts(${expr})", { label: "scripts", type: "function", info: "Scripts (Math)" }),
    snippetCompletion("limits(${expr})", { label: "limits", type: "function", info: "Limits (Math)" }),
    snippetCompletion("op(\"${name}\")", { label: "op", type: "function", info: "Operator (Math)" }),
    snippetCompletion("lr(${expr})", { label: "lr", type: "function", info: "Left/Right scales (Math)" }),
    snippetCompletion("mid(${|})", { label: "mid", type: "function", info: "Mid delimiter (Math)" })
];

export function typstCompletions(context: CompletionContext) {
  const word = context.matchBefore(/[\w#]*/);
  if (!word || (word.from === word.to && !context.explicit)) return null;

  return {
    from: word.text.startsWith("#") ? word.from + 1 : word.from,
    options: typstOptions,
    validFor: /^[\w]*$/,
  };
}
